security:
    providers:
        in_memory:
            memory:
                users:
                    bogdan:
                        password: 1337
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: ~
            pattern: ^/admin/*
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin_dashboard
            logout:
                path:   /admin/logout
                target: /
        main:
            anonymous: true
    access_control:
         - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/*, roles: ROLE_ADMIN }
